version: '3.3'
services:
    postgres:
        image: postgres:14
        restart: always
        environment:
          - POSTGRES_USER=cape
          - POSTGRES_PASSWORD=s3Cur1Ty
          - POSTGRES_DB=cape
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    mongo:
      image: mongo:5.0.6
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: s3Cur1Ty
      volumes: 
          - ./mongo:/data/db
    cape:
        build : .
        image: cape/cape
        restart: always
        environment:
          - MONGO_HOST=mongo
          - RESULTSERVER_HOST='0.0.0.0'
          - RESULTSERVER_PORT="2042"
          - DATABASE_CONNECTION="postgresql://cape:s3Cur1Ty@postgres:5432/cape"
          - MACHINERY=kvm
        ports:
          - '8088:80'
        volumes: 
          - ./conf:/opt/CAPEv2/conf
        depends_on:
          - postgres
          - mongo